name: deploy website
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 6.32.4

      - name: Set node version to 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'pnpm'

      - run: pnpm install

      - name: build
        run: pnpm build

      - uses: amondnet/vercel-action@v20 #deploy
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} 
          github-token: ${{ secrets.GITHUB_TOKEN }}  
          vercel-args: '--prod' 
          vercel-org-id: ${{ secrets.ORG_ID}}  
          vercel-project-id: ${{ secrets.PROJECT_ID}} 
          working-directory: ./dist/