name: 'ci'
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Set node version to 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'pnpm'

      - run: pnpm install

      - name: Cypress run
            uses: cypress-io/github-action@v4
            with:
              build: pnpm build
              start: pnpm preview
              browser: chrome
